events_events:
    resource: "@EventsEventsBundle/Controller/"
    type:     annotation
    prefix:   /

# app/config/routing.yml
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
 
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /adm    